brazillian_ecom:
  outputs:
    laptop:
      type: sqlite
      threads: 1
      database: dbt_databricks
      schema: 'main'
      schemas_and_paths:
        main: '../data/dbt_databricks'
      schema_directory: '../data'

    dev:
      catalog: null
      host: adb-your-host-name.azuredatabricks.net
      http_path: sql/protocolv1/o/your-host-name/1111-111111-abz234ha
      schema: brazillian_ecom
      threads: 1
      token: 123456789abcdefghijklmnopqrstuvwxyz
      type: databricks
  target: laptop